cicd added

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -2,20 +2,28 @@ name: workflow
 
 on:
   push:
-    - main
-  paths-ignore:
-    - 'README.md'
+    branches:
+      - main
+    paths-ignore:
+      - 'README.md'
 
 permissions:
   id-token: write
   contents: read
 
-
 jobs:
+
+  # ==========================================
+  # CONTINUOUS INTEGRATION
+  # ==========================================
   integration:
+
     name: Continuous Integration
+
     runs-on: ubuntu-latest
+
     steps:
+
       - name: Checkout code
         uses: actions/checkout@v3
 
@@ -25,11 +33,19 @@ jobs:
       - name: Run unit tests
         run: echo "Running Unit Tests"
 
+  # ==========================================
+  # BUILD AND PUSH IMAGE TO AWS ECR
+  # ==========================================
   build-and-push-ecr-image:
+
     name: Continuous Delivery
+
     needs: integration
+
     runs-on: ubuntu-latest
+
     steps:
+
       - name: Checkout code
         uses: actions/checkout@v3
 
@@ -37,56 +53,92 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y unzip
+
+      # Configure AWS Credentials
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
+      # Login to AWS ECR
       - name: Login to Amazon ECR
         id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+        uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Build, Tag, and Push Docker Image to Amazon ECR
-        id: build-image
+      # Build Docker Image
+      - name: Build Docker Image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
-          IMAGE_TAG: ${{ github.sha }}
+          IMAGE_TAG: latest
+
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+
+      # Push Docker Image
+      - name: Push Docker Image to ECR
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+          IMAGE_TAG: latest
+
+        run: |
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 
-
+  # ==========================================
+  # CONTINUOUS DEPLOYMENT
+  # ==========================================
   Continuous-Deployment:
+
+    name: Continuous Deployment
+
     needs: build-and-push-ecr-image
+
     runs-on: self-hosted
+
     steps:
-      - name: Checkout
+
+      - name: Checkout code
         uses: actions/checkout@v3
 
+      # Configure AWS Credentials
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
+      # Login to AWS ECR
       - name: Login to Amazon ECR
         id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+        uses: aws-actions/amazon-ecr-login@v2
 
-
-      - name: Pull latest images
-        run:
-          docker pull ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
-
-
-      - name: Run Docker Image to serve users
+      # Pull Latest Image
+      - name: Pull latest image
         run: |
-          docker run -d -p 8080:8080 --name=cnncls -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
-      - name: Clean Previous images and containers
+          docker pull \
+          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
+
+      # Stop Existing Container
+      - name: Stop old container
+        run: |
+          docker stop cnncls || true
+          docker rm cnncls || true
+
+      # Run New Container
+      - name: Run Docker Container
+        run: |
+          docker run -d \
+          -p 8080:8080 \
+          --name cnncls \
+          -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
+          -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
+          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
+
+      # Cleanup
+      - name: Clean old Docker images
         run: |
           docker system prune -f
